// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleCarDb.Data;

#nullable disable

namespace SimpleCarDb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260723114207_FinalSync")]
    partial class FinalSync
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimpleCarDb.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Audi"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mercedes-Benz"
                        });
                });

            modelBuilder.Entity("SimpleCarDb.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            Name = "320d",
                            Type = "Dízel"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            Name = "M3",
                            Type = "Benzin"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 2,
                            Name = "Corolla",
                            Type = "Teljes Hibrid (HEV)"
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 2,
                            Name = "RAV4",
                            Type = "Plug-in Hibrid (PHEV)"
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 3,
                            Name = "Mustang",
                            Type = "V8 Benzin"
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 3,
                            Name = "F-150",
                            Type = "Benzin"
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 4,
                            Name = "A4",
                            Type = "Dízel"
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 4,
                            Name = "RS6",
                            Type = "Benzin"
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 5,
                            Name = "EQE",
                            Type = "Elektromos (BEV)"
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 5,
                            Name = "C220",
                            Type = "Mild Hibrid (MHEV)"
                        });
                });

            modelBuilder.Entity("SimpleCarDb.Models.EngineDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacityCc")
                        .HasColumnType("int");

                    b.Property<int?>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("EngineNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Horsepower")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId")
                        .IsUnique()
                        .HasFilter("[CarId] IS NOT NULL");

                    b.ToTable("EngineDetails");
                });

            modelBuilder.Entity("SimpleCarDb.Models.Car", b =>
                {
                    b.HasOne("SimpleCarDb.Models.Brand", "Brand")
                        .WithMany("Cars")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("SimpleCarDb.Models.EngineDetail", b =>
                {
                    b.HasOne("SimpleCarDb.Models.Car", "Car")
                        .WithOne("EngineDetail")
                        .HasForeignKey("SimpleCarDb.Models.EngineDetail", "CarId");

                    b.Navigation("Car");
                });

            modelBuilder.Entity("SimpleCarDb.Models.Brand", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("SimpleCarDb.Models.Car", b =>
                {
                    b.Navigation("EngineDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
