// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleCarDb.Data;

#nullable disable

namespace SimpleCarDb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260723113311_MakeCarIdNullable2")]
    partial class MakeCarIdNullable2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimpleCarDb.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Audi"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mercedes-Benz"
                        });
                });

            modelBuilder.Entity("SimpleCarDb.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            Name = "320d",
                            Type = "Dízel"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            Name = "M3",
                            Type = "Benzin"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 2,
                            Name = "Corolla",
                            Type = "Teljes Hibrid (HEV)"
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 2,
                            Name = "RAV4",
                            Type = "Plug-in Hibrid (PHEV)"
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 3,
                            Name = "Mustang",
                            Type = "V8 Benzin"
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 3,
                            Name = "F-150",
                            Type = "Benzin"
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 4,
                            Name = "A4",
                            Type = "Dízel"
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 4,
                            Name = "RS6",
                            Type = "Benzin"
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 5,
                            Name = "EQE",
                            Type = "Elektromos (BEV)"
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 5,
                            Name = "C220",
                            Type = "Mild Hibrid (MHEV)"
                        });
                });

            modelBuilder.Entity("SimpleCarDb.Models.EngineDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacityCc")
                        .HasColumnType("int");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("EngineNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Horsepower")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId")
                        .IsUnique();

                    b.ToTable("EngineDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapacityCc = 1995,
                            CarId = 1,
                            EngineNumber = "B47D20A123456",
                            Horsepower = 190
                        },
                        new
                        {
                            Id = 2,
                            CapacityCc = 2993,
                            CarId = 2,
                            EngineNumber = "S58B30A654321",
                            Horsepower = 510
                        },
                        new
                        {
                            Id = 3,
                            CapacityCc = 1798,
                            CarId = 3,
                            EngineNumber = "2ZRFXE987654",
                            Horsepower = 122
                        },
                        new
                        {
                            Id = 4,
                            CapacityCc = 2487,
                            CarId = 4,
                            EngineNumber = "A25AFXS456789",
                            Horsepower = 306
                        },
                        new
                        {
                            Id = 5,
                            CapacityCc = 5038,
                            CarId = 5,
                            EngineNumber = "COY50V8112233",
                            Horsepower = 450
                        },
                        new
                        {
                            Id = 6,
                            CapacityCc = 3496,
                            CarId = 6,
                            EngineNumber = "ECO35V6998877",
                            Horsepower = 400
                        },
                        new
                        {
                            Id = 7,
                            CapacityCc = 1968,
                            CarId = 7,
                            EngineNumber = "DEUA20TDI3344",
                            Horsepower = 204
                        },
                        new
                        {
                            Id = 8,
                            CapacityCc = 3996,
                            CarId = 8,
                            EngineNumber = "DBCV40TFSI667",
                            Horsepower = 600
                        },
                        new
                        {
                            Id = 9,
                            CapacityCc = 0,
                            CarId = 9,
                            EngineNumber = "EM0004ELEC112",
                            Horsepower = 292
                        },
                        new
                        {
                            Id = 10,
                            CapacityCc = 1993,
                            CarId = 10,
                            EngineNumber = "OM65420D99001",
                            Horsepower = 200
                        });
                });

            modelBuilder.Entity("SimpleCarDb.Models.Car", b =>
                {
                    b.HasOne("SimpleCarDb.Models.Brand", "Brand")
                        .WithMany("Cars")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("SimpleCarDb.Models.EngineDetail", b =>
                {
                    b.HasOne("SimpleCarDb.Models.Car", "Car")
                        .WithOne("EngineDetail")
                        .HasForeignKey("SimpleCarDb.Models.EngineDetail", "CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("SimpleCarDb.Models.Brand", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("SimpleCarDb.Models.Car", b =>
                {
                    b.Navigation("EngineDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
